# Generated by Django 3.1.14 on 2022-11-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221024_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
